export interface FAQ {
  question: string;
  answer: string;
}

export interface Tool {
  slug: string;
  name: string;
  description: string;
  shortDescription: string;
  category: string;
  categoryName: string;
  keywords: string[];
  icon: string;
  color: string;
  gradient: string;
  features: Array<{ title: string; description: string; icon: string }>;
  howTo: Array<{ step: number; title: string; description: string }>;
  faqs: FAQ[];
  relatedTools: string[];
  benefits: string[];
}

export const tools: Tool[] = [
  // ── IMAGE TOOLS ───────────────────────────────────────────────────────────
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description:
      "Compress images online without losing quality. Reduce PNG, JPG, and WebP file sizes up to 90% for faster websites and easier sharing.",
    shortDescription: "Compress images up to 90% without quality loss.",
    category: "image-tools",
    categoryName: "Image Tools",
    keywords: ["image compressor", "compress image online", "reduce image size", "png compressor", "jpg compressor"],
    icon: "ImageDown",
    color: "text-violet-500",
    gradient: "from-violet-500 to-purple-600",
    features: [
      { title: "Lossless Compression", description: "Reduce file size while maintaining visual quality.", icon: "Zap" },
      { title: "Multiple Formats", description: "Compress PNG, JPG, WebP, and GIF images.", icon: "Image" },
      { title: "Batch Processing", description: "Compress multiple images simultaneously.", icon: "Layers" },
      { title: "Privacy First", description: "All processing happens in your browser.", icon: "Shield" },
    ],
    howTo: [
      { step: 1, title: "Upload Your Image", description: "Click or drag-and-drop your image file." },
      { step: 2, title: "Set Quality Level", description: "Choose compression level from 1–100." },
      { step: 3, title: "Download", description: "Click compress and download your optimized image." },
    ],
    faqs: [
      { question: "Does compression reduce image quality?", answer: "Our smart compression minimizes visible quality loss. You can control the compression level to balance size vs. quality." },
      { question: "What formats can I compress?", answer: "We support JPG, PNG, WebP, and GIF image formats." },
      { question: "Is there a file size limit?", answer: "You can compress images up to 10MB per file." },
      { question: "Is the tool free?", answer: "Yes, completely free with no sign-up required." },
      { question: "Are my images stored on your servers?", answer: "No. Compression happens entirely in your browser. Your images never leave your device." },
    ],
    relatedTools: ["image-resizer", "webp-converter", "png-to-jpg"],
    benefits: ["Faster page load times", "Lower bandwidth usage", "Better Core Web Vitals", "Easy social media sharing"],
  },
  {
    slug: "background-remover",
    name: "Background Remover",
    description:
      "Remove image backgrounds automatically online for free. Perfect for product photos, profile pictures, and graphic design.",
    shortDescription: "Remove image backgrounds automatically in seconds.",
    category: "image-tools",
    categoryName: "Image Tools",
    keywords: ["background remover", "remove background from image", "transparent background", "bg remover free"],
    icon: "Scissors",
    color: "text-violet-500",
    gradient: "from-violet-500 to-purple-600",
    features: [
      { title: "AI-Powered", description: "Smart AI detects and removes backgrounds accurately.", icon: "Cpu" },
      { title: "Transparent PNG", description: "Output as PNG with transparent background.", icon: "Image" },
      { title: "No Watermark", description: "Download clean images without watermarks.", icon: "Check" },
      { title: "Fast Processing", description: "Background removed in seconds.", icon: "Zap" },
    ],
    howTo: [
      { step: 1, title: "Upload Image", description: "Upload the image you want to process." },
      { step: 2, title: "Auto Remove", description: "Background is automatically detected and removed." },
      { step: 3, title: "Download", description: "Download the transparent PNG result." },
    ],
    faqs: [
      { question: "What types of images work best?", answer: "Images with clear subjects like people, products, and objects against distinct backgrounds work best." },
      { question: "Is the background removal accurate?", answer: "Our tool handles most common images accurately. Complex edges like hair may need manual refinement." },
      { question: "What format is the output?", answer: "Output is always PNG with a transparent background." },
      { question: "Is this tool free?", answer: "Yes, completely free with no account required." },
      { question: "Can I remove backgrounds from multiple images?", answer: "Yes, you can process images one by one for free." },
    ],
    relatedTools: ["image-compressor", "png-to-jpg", "image-resizer"],
    benefits: ["Professional product photos", "Clean profile pictures", "Graphic design assets", "E-commerce ready images"],
  },
  {
    slug: "webp-converter",
    name: "WebP Converter",
    description:
      "Convert images to WebP format online for free. WebP images are 25–35% smaller than PNG and JPG while maintaining quality.",
    shortDescription: "Convert PNG/JPG to WebP for faster websites.",
    category: "image-tools",
    categoryName: "Image Tools",
    keywords: ["webp converter", "convert to webp", "jpg to webp", "png to webp", "webp format"],
    icon: "RefreshCw",
    color: "text-violet-500",
    gradient: "from-violet-500 to-purple-600",
    features: [
      { title: "Smaller File Sizes", description: "WebP is 25-35% smaller than comparable PNG/JPG.", icon: "TrendingDown" },
      { title: "Quality Preserved", description: "Convert without noticeable quality loss.", icon: "Star" },
      { title: "Instant Conversion", description: "Convert images in seconds in your browser.", icon: "Zap" },
      { title: "Batch Convert", description: "Convert multiple images at once.", icon: "Layers" },
    ],
    howTo: [
      { step: 1, title: "Upload Image", description: "Upload your PNG, JPG, or GIF file." },
      { step: 2, title: "Set Quality", description: "Choose output quality level." },
      { step: 3, title: "Convert & Download", description: "Click convert and download your WebP file." },
    ],
    faqs: [
      { question: "Why use WebP format?", answer: "WebP provides superior compression, resulting in smaller file sizes and faster website load times compared to PNG and JPG." },
      { question: "Is WebP supported by all browsers?", answer: "WebP is supported by all modern browsers including Chrome, Firefox, Safari, and Edge." },
      { question: "Can I convert WebP back to JPG?", answer: "Use our JPG to PNG or image converter tools to convert WebP back to other formats." },
      { question: "Does the conversion reduce quality?", answer: "We use high-quality conversion settings that preserve visual quality while reducing file size." },
      { question: "Is this tool free?", answer: "Yes, 100% free with no registration needed." },
    ],
    relatedTools: ["image-compressor", "png-to-jpg", "jpg-to-png"],
    benefits: ["Faster website loading", "Better SEO scores", "Reduced bandwidth costs", "Modern browser support"],
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG Converter",
    description:
      "Convert PNG images to JPG format online for free. Reduce file sizes and improve compatibility with this fast, browser-based tool.",
    shortDescription: "Convert PNG images to JPG format instantly.",
    category: "image-tools",
    categoryName: "Image Tools",
    keywords: ["png to jpg", "convert png to jpeg", "png to jpg converter free", "png jpg online"],
    icon: "ArrowRightLeft",
    color: "text-violet-500",
    gradient: "from-violet-500 to-purple-600",
    features: [
      { title: "Fast Conversion", description: "Convert PNG to JPG in seconds.", icon: "Zap" },
      { title: "Quality Control", description: "Set JPG quality from 1–100.", icon: "SlidersHorizontal" },
      { title: "No Upload", description: "All processing happens in your browser.", icon: "Shield" },
      { title: "Free Forever", description: "No limits, no fees, no account needed.", icon: "Check" },
    ],
    howTo: [
      { step: 1, title: "Upload PNG", description: "Select or drag-and-drop your PNG file." },
      { step: 2, title: "Adjust Quality", description: "Set your desired JPG quality level." },
      { step: 3, title: "Download JPG", description: "Download the converted JPG image." },
    ],
    faqs: [
      { question: "Will converting PNG to JPG lose transparency?", answer: "Yes, JPG does not support transparency. Transparent areas will be filled with white background." },
      { question: "What quality should I use?", answer: "80-90 quality gives a good balance of file size and visual quality for most use cases." },
      { question: "Can I convert multiple files?", answer: "You can convert files one at a time using our free tool." },
      { question: "Is the converter free?", answer: "Yes, completely free with unlimited conversions." },
      { question: "Are my files uploaded to your servers?", answer: "No, all conversion happens locally in your browser." },
    ],
    relatedTools: ["jpg-to-png", "image-compressor", "webp-converter"],
    benefits: ["Smaller file sizes", "Better email compatibility", "Universal format support", "Fast sharing"],
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG Converter",
    description:
      "Convert JPG images to PNG format online for free. Get lossless quality and transparency support with this instant browser-based converter.",
    shortDescription: "Convert JPG images to lossless PNG format.",
    category: "image-tools",
    categoryName: "Image Tools",
    keywords: ["jpg to png", "convert jpg to png", "jpeg to png converter", "jpg png online free"],
    icon: "ArrowRightLeft",
    color: "text-violet-500",
    gradient: "from-violet-500 to-purple-600",
    features: [
      { title: "Lossless Output", description: "PNG preserves image quality perfectly.", icon: "Star" },
      { title: "Transparency Support", description: "PNG supports transparent backgrounds.", icon: "Image" },
      { title: "Instant Convert", description: "Conversion happens instantly in browser.", icon: "Zap" },
      { title: "Free & Private", description: "No uploads, no accounts, completely free.", icon: "Shield" },
    ],
    howTo: [
      { step: 1, title: "Upload JPG", description: "Select or drag-and-drop your JPG/JPEG file." },
      { step: 2, title: "Convert", description: "Click convert to process the image." },
      { step: 3, title: "Download PNG", description: "Download your converted PNG file." },
    ],
    faqs: [
      { question: "Why convert JPG to PNG?", answer: "PNG is lossless, meaning no quality is lost. It also supports transparency, making it ideal for logos and graphics." },
      { question: "Will the image quality improve?", answer: "Converting to PNG prevents further quality loss but won't restore quality already lost during JPG compression." },
      { question: "Is the converter free?", answer: "Yes, 100% free with no sign-up required." },
      { question: "Are my files sent to a server?", answer: "No, all conversion happens in your browser for maximum privacy." },
      { question: "What is the maximum file size?", answer: "You can convert JPG files up to 20MB." },
    ],
    relatedTools: ["png-to-jpg", "image-compressor", "webp-converter"],
    benefits: ["Lossless quality", "Transparency support", "Better for editing", "High fidelity graphics"],
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description:
      "Resize images online for free to any dimension. Perfect for social media, websites, email, and print. Maintain aspect ratio automatically.",
    shortDescription: "Resize images to any dimension instantly online.",
    category: "image-tools",
    categoryName: "Image Tools",
    keywords: ["image resizer", "resize image online", "image resize free", "resize photo", "change image dimensions"],
    icon: "Maximize2",
    color: "text-violet-500",
    gradient: "from-violet-500 to-purple-600",
    features: [
      { title: "Custom Dimensions", description: "Set exact width and height in pixels.", icon: "Ruler" },
      { title: "Aspect Ratio Lock", description: "Maintain proportions automatically.", icon: "Lock" },
      { title: "Preset Sizes", description: "Social media presets for quick resizing.", icon: "Layout" },
      { title: "Browser-Based", description: "No upload required. Fast and private.", icon: "Shield" },
    ],
    howTo: [
      { step: 1, title: "Upload Image", description: "Select or drag-and-drop your image." },
      { step: 2, title: "Set Dimensions", description: "Enter target width and height or choose a preset." },
      { step: 3, title: "Download", description: "Download the resized image." },
    ],
    faqs: [
      { question: "Can I resize multiple images at once?", answer: "Currently the tool supports one image at a time. Batch resizing is coming soon." },
      { question: "Will resizing reduce quality?", answer: "Enlarging images may reduce quality. Reducing size generally preserves quality." },
      { question: "What formats are supported?", answer: "We support JPG, PNG, WebP, and GIF images." },
      { question: "Can I lock the aspect ratio?", answer: "Yes, enable aspect ratio lock to maintain original proportions while resizing." },
      { question: "Is the tool free?", answer: "Yes, completely free with no registration." },
    ],
    relatedTools: ["image-compressor", "png-to-jpg", "webp-converter"],
    benefits: ["Social media optimization", "Website performance", "Email-ready images", "Print preparation"],
  },

  // ── FINANCE TOOLS ─────────────────────────────────────────────────────────
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    description:
      "Calculate SIP (Systematic Investment Plan) returns online. Estimate maturity amount, total investment, and wealth gained over any period.",
    shortDescription: "Calculate SIP mutual fund returns and maturity amount.",
    category: "finance-tools",
    categoryName: "Finance Tools",
    keywords: ["sip calculator", "systematic investment plan calculator", "mutual fund sip returns", "sip maturity calculator"],
    icon: "TrendingUp",
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
    features: [
      { title: "Accurate Returns", description: "Uses standard compound interest formula.", icon: "Calculator" },
      { title: "Visual Chart", description: "See investment vs returns in a chart.", icon: "BarChart2" },
      { title: "Inflation Adjusted", description: "Account for inflation in projections.", icon: "TrendingDown" },
      { title: "Instant Results", description: "Real-time calculation as you type.", icon: "Zap" },
    ],
    howTo: [
      { step: 1, title: "Enter Monthly SIP", description: "Enter the monthly SIP amount you plan to invest." },
      { step: 2, title: "Set Expected Return", description: "Enter the expected annual return rate (%)." },
      { step: 3, title: "Choose Duration", description: "Set the investment duration in years." },
    ],
    faqs: [
      { question: "What is SIP?", answer: "SIP (Systematic Investment Plan) is a method of investing a fixed amount regularly in mutual funds, typically monthly." },
      { question: "How is SIP return calculated?", answer: "SIP returns are calculated using compound interest: M = P × [{(1+i)^n – 1}/i] × (1+i), where i is monthly rate and n is months." },
      { question: "Is the SIP calculator accurate?", answer: "Yes, it uses the standard mathematical formula. Actual returns depend on market performance." },
      { question: "What is a good SIP return rate?", answer: "Equity mutual funds have historically returned 12–15% annually in India over long periods." },
      { question: "Can I calculate SIP for 30 years?", answer: "Yes, enter any duration up to 40 years to see long-term projections." },
    ],
    relatedTools: ["emi-calculator", "compound-interest-calculator", "roi-calculator"],
    benefits: ["Plan retirement savings", "Track wealth creation", "Compare investment scenarios", "Visualize compound growth"],
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    description:
      "Calculate loan EMI (Equated Monthly Installment) online instantly. Works for home loans, car loans, personal loans, and education loans.",
    shortDescription: "Calculate monthly EMI for any loan instantly.",
    category: "finance-tools",
    categoryName: "Finance Tools",
    keywords: ["emi calculator", "loan emi calculator", "home loan emi", "car loan emi", "monthly installment calculator"],
    icon: "CreditCard",
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
    features: [
      { title: "All Loan Types", description: "Works for home, car, personal, and education loans.", icon: "Building" },
      { title: "Amortization Table", description: "See month-by-month breakdown of payments.", icon: "Table" },
      { title: "Total Interest", description: "See total interest payable over loan tenure.", icon: "IndianRupee" },
      { title: "Real-Time Calc", description: "Instant results as you change inputs.", icon: "Zap" },
    ],
    howTo: [
      { step: 1, title: "Enter Loan Amount", description: "Enter the principal loan amount." },
      { step: 2, title: "Enter Interest Rate", description: "Enter the annual interest rate (%)." },
      { step: 3, title: "Set Tenure", description: "Enter the loan duration in months or years." },
    ],
    faqs: [
      { question: "What is EMI?", answer: "EMI (Equated Monthly Installment) is the fixed monthly payment made to repay a loan over a set period." },
      { question: "How is EMI calculated?", answer: "EMI = [P × r × (1+r)^n] / [(1+r)^n – 1], where P is principal, r is monthly rate, and n is number of months." },
      { question: "Does the calculator account for processing fees?", answer: "The basic EMI calculation doesn't include fees. Add fees to your loan amount for a complete picture." },
      { question: "Can I calculate home loan EMI?", answer: "Yes, enter your home loan amount, rate, and tenure to get your monthly EMI." },
      { question: "What if interest rate changes (floating rate)?", answer: "Our calculator is for fixed rates. For floating rates, recalculate whenever your rate changes." },
    ],
    relatedTools: ["sip-calculator", "mortgage-calculator", "loan-calculator"],
    benefits: ["Plan monthly budget", "Compare loan offers", "Understand total cost", "Make informed decisions"],
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    description:
      "Calculate compound interest online for any principal, rate, and time period. See how your money grows with daily, monthly, or yearly compounding.",
    shortDescription: "Calculate compound interest for investments and savings.",
    category: "finance-tools",
    categoryName: "Finance Tools",
    keywords: ["compound interest calculator", "ci calculator", "compound interest formula", "interest calculator online"],
    icon: "TrendingUp",
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
    features: [
      { title: "Multiple Frequencies", description: "Daily, monthly, quarterly, or annual compounding.", icon: "Calendar" },
      { title: "Visual Growth", description: "Chart showing money growth over time.", icon: "BarChart2" },
      { title: "Formula Shown", description: "See the exact formula used for calculation.", icon: "Calculator" },
      { title: "Simple vs Compound", description: "Compare simple and compound interest.", icon: "GitCompare" },
    ],
    howTo: [
      { step: 1, title: "Enter Principal", description: "Enter your initial investment amount." },
      { step: 2, title: "Set Rate & Time", description: "Enter annual interest rate and time period." },
      { step: 3, title: "Choose Frequency", description: "Select compounding frequency and calculate." },
    ],
    faqs: [
      { question: "What is compound interest?", answer: "Compound interest is interest calculated on both the initial principal and the accumulated interest from previous periods." },
      { question: "What is the compound interest formula?", answer: "A = P(1 + r/n)^(nt), where P is principal, r is annual rate, n is compounds per year, and t is years." },
      { question: "What compounding frequency is best?", answer: "More frequent compounding yields more returns. Daily compounding gives slightly more than annual compounding." },
      { question: "Is compound interest better than simple interest?", answer: "Yes, compound interest grows faster because interest earns interest, especially over long periods." },
      { question: "Can I calculate for fractional years?", answer: "Yes, you can enter decimal values for time (e.g., 1.5 years)." },
    ],
    relatedTools: ["sip-calculator", "roi-calculator", "cagr-calculator"],
    benefits: ["Understand wealth growth", "Plan savings goals", "Compare investment options", "Learn about compounding"],
  },
  {
    slug: "mortgage-calculator",
    name: "Mortgage Calculator",
    description:
      "Calculate your monthly mortgage payment, total interest, and amortization schedule online for free. Plan your home purchase with confidence.",
    shortDescription: "Calculate monthly mortgage payments and total interest.",
    category: "finance-tools",
    categoryName: "Finance Tools",
    keywords: ["mortgage calculator", "home loan calculator", "mortgage payment calculator", "monthly mortgage calculator"],
    icon: "Home",
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
    features: [
      { title: "Payment Breakdown", description: "See principal vs interest split.", icon: "PieChart" },
      { title: "Amortization", description: "Full amortization schedule for the loan.", icon: "Table" },
      { title: "Down Payment", description: "Factor in your down payment amount.", icon: "Landmark" },
      { title: "Extra Payments", description: "See how extra payments reduce your tenure.", icon: "TrendingDown" },
    ],
    howTo: [
      { step: 1, title: "Enter Home Price", description: "Enter the total home purchase price." },
      { step: 2, title: "Down Payment", description: "Enter your down payment amount or percentage." },
      { step: 3, title: "Loan Terms", description: "Enter interest rate and loan tenure." },
    ],
    faqs: [
      { question: "What is a mortgage?", answer: "A mortgage is a loan used to purchase real estate, where the property serves as collateral." },
      { question: "How much down payment is needed?", answer: "Typically 20% is recommended, but some loans allow as little as 3-5% down." },
      { question: "What is the difference between EMI and mortgage?", answer: "EMI is the generic term for monthly loan payments. Mortgage specifically refers to home loan payments." },
      { question: "Should I choose a fixed or floating rate?", answer: "Fixed rates offer payment stability. Floating rates can be lower initially but vary with market conditions." },
      { question: "How do I reduce my mortgage payment?", answer: "Increase your down payment, choose a longer tenure, or negotiate a lower interest rate." },
    ],
    relatedTools: ["emi-calculator", "loan-calculator", "compound-interest-calculator"],
    benefits: ["Plan home purchase", "Budget monthly expenses", "Compare lenders", "Understand true loan cost"],
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description:
      "Calculate loan payments, total interest, and repayment schedule for any loan type. Fast, accurate, and completely free online.",
    shortDescription: "Calculate payments and interest for any loan type.",
    category: "finance-tools",
    categoryName: "Finance Tools",
    keywords: ["loan calculator", "personal loan calculator", "loan repayment calculator", "loan interest calculator"],
    icon: "Banknote",
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
    features: [
      { title: "All Loan Types", description: "Personal, auto, business, and more.", icon: "CreditCard" },
      { title: "Total Cost", description: "See full repayment cost including interest.", icon: "IndianRupee" },
      { title: "Comparison Mode", description: "Compare two loan scenarios side by side.", icon: "GitCompare" },
      { title: "Schedule Export", description: "Export repayment schedule as CSV.", icon: "Download" },
    ],
    howTo: [
      { step: 1, title: "Enter Loan Details", description: "Input principal amount, interest rate, and tenure." },
      { step: 2, title: "Calculate", description: "Click calculate to see monthly payment and totals." },
      { step: 3, title: "View Schedule", description: "Review the complete repayment amortization." },
    ],
    faqs: [
      { question: "How is loan interest calculated?", answer: "Using the formula: EMI = [P × r × (1+r)^n] / [(1+r)^n-1], where P is principal, r is monthly rate, and n is months." },
      { question: "What is the typical personal loan rate?", answer: "Personal loan rates in India range from 10–24% annually depending on the lender and credit score." },
      { question: "Can I prepay my loan?", answer: "Most loans allow prepayment, but check with your lender for prepayment charges." },
      { question: "How long can a loan tenure be?", answer: "Personal loans: up to 7 years. Home loans: up to 30 years. Car loans: up to 7 years." },
      { question: "Does a higher credit score reduce EMI?", answer: "Yes, higher credit scores often qualify for lower interest rates, which reduces your EMI." },
    ],
    relatedTools: ["emi-calculator", "mortgage-calculator", "sip-calculator"],
    benefits: ["Smart loan planning", "Find best loan terms", "Budget repayments", "Avoid over-borrowing"],
  },
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    description:
      "Calculate Return on Investment (ROI) online for any investment. Determine profitability, annualized returns, and investment efficiency instantly.",
    shortDescription: "Calculate ROI and annualized returns for any investment.",
    category: "finance-tools",
    categoryName: "Finance Tools",
    keywords: ["roi calculator", "return on investment calculator", "investment return calculator", "roi formula calculator"],
    icon: "BarChart2",
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
    features: [
      { title: "Simple ROI", description: "Calculate basic ROI percentage instantly.", icon: "Percent" },
      { title: "Annualized ROI", description: "Calculate annualized returns for comparison.", icon: "Calendar" },
      { title: "Net Profit", description: "See net profit and total gain/loss.", icon: "TrendingUp" },
      { title: "Benchmark Compare", description: "Compare against benchmark returns.", icon: "GitCompare" },
    ],
    howTo: [
      { step: 1, title: "Enter Investment", description: "Enter your initial investment amount." },
      { step: 2, title: "Enter Return", description: "Enter the final value or gain amount." },
      { step: 3, title: "Calculate", description: "Get your ROI percentage and annualized return." },
    ],
    faqs: [
      { question: "What is ROI?", answer: "ROI (Return on Investment) measures the gain or loss from an investment relative to its cost, expressed as a percentage." },
      { question: "What is the ROI formula?", answer: "ROI = [(Final Value - Initial Cost) / Initial Cost] × 100" },
      { question: "What is a good ROI?", answer: "ROI depends on investment type. Stock market averages 10–12% annually; real estate varies by location." },
      { question: "What is annualized ROI?", answer: "Annualized ROI adjusts for the time period, allowing comparison of investments over different durations." },
      { question: "Does ROI account for taxes?", answer: "Our basic calculator doesn't include taxes. For net ROI, subtract applicable capital gains tax." },
    ],
    relatedTools: ["cagr-calculator", "sip-calculator", "compound-interest-calculator"],
    benefits: ["Evaluate investments", "Compare opportunities", "Make data-driven decisions", "Track portfolio performance"],
  },
  {
    slug: "cagr-calculator",
    name: "CAGR Calculator",
    description:
      "Calculate CAGR (Compound Annual Growth Rate) online for investments, revenue, and more. Understand the true annual growth of any value.",
    shortDescription: "Calculate Compound Annual Growth Rate for any investment.",
    category: "finance-tools",
    categoryName: "Finance Tools",
    keywords: ["cagr calculator", "compound annual growth rate calculator", "cagr formula", "investment growth rate"],
    icon: "TrendingUp",
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
    features: [
      { title: "Simple Interface", description: "Enter 3 values and get instant CAGR.", icon: "Calculator" },
      { title: "Future Projection", description: "Project future value using CAGR.", icon: "TrendingUp" },
      { title: "Benchmark", description: "Compare against market benchmarks.", icon: "BarChart2" },
      { title: "Visual Chart", description: "See growth visualized over time.", icon: "LineChart" },
    ],
    howTo: [
      { step: 1, title: "Enter Start Value", description: "Enter the initial value or investment amount." },
      { step: 2, title: "Enter End Value", description: "Enter the final value after growth." },
      { step: 3, title: "Enter Period", description: "Enter the number of years and calculate." },
    ],
    faqs: [
      { question: "What is CAGR?", answer: "CAGR (Compound Annual Growth Rate) represents the rate at which an investment grows annually, assuming it compounds over time." },
      { question: "What is the CAGR formula?", answer: "CAGR = (Ending Value / Beginning Value)^(1/Years) - 1" },
      { question: "Is CAGR the same as average annual return?", answer: "No. CAGR is a smoothed rate ignoring volatility. Average return adds all yearly returns and divides by years." },
      { question: "What CAGR is good for stocks?", answer: "A CAGR of 12–15% is considered excellent for equity investments over 10+ year periods in India." },
      { question: "Can CAGR be negative?", answer: "Yes, if the ending value is less than the starting value, CAGR will be negative indicating a loss." },
    ],
    relatedTools: ["roi-calculator", "sip-calculator", "compound-interest-calculator"],
    benefits: ["Evaluate investment performance", "Compare funds", "Set realistic goals", "Analyze business growth"],
  },
  {
    slug: "gst-calculator",
    name: "GST Calculator",
    description:
      "Calculate GST (Goods and Services Tax) online for any amount. Add or remove GST at 5%, 12%, 18%, or 28% rates instantly.",
    shortDescription: "Calculate GST inclusive and exclusive amounts instantly.",
    category: "finance-tools",
    categoryName: "Finance Tools",
    keywords: ["gst calculator", "gst calculation online", "gst inclusive exclusive", "goods services tax calculator india"],
    icon: "Receipt",
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
    features: [
      { title: "Add or Remove GST", description: "Calculate GST inclusive or exclusive.", icon: "PlusCircle" },
      { title: "All GST Rates", description: "5%, 12%, 18%, and 28% GST slabs.", icon: "Percent" },
      { title: "CGST + SGST Split", description: "See CGST and SGST breakdown.", icon: "Divide" },
      { title: "Bulk Calculation", description: "Calculate for multiple items.", icon: "List" },
    ],
    howTo: [
      { step: 1, title: "Enter Amount", description: "Enter the base amount or GST-inclusive amount." },
      { step: 2, title: "Select GST Rate", description: "Choose the applicable GST rate (5/12/18/28%)." },
      { step: 3, title: "Calculate", description: "See GST amount, CGST, SGST, and total instantly." },
    ],
    faqs: [
      { question: "What is GST?", answer: "GST (Goods and Services Tax) is an indirect tax levied on the supply of goods and services in India, replacing multiple taxes." },
      { question: "What are the GST rates?", answer: "GST has 4 main slabs: 5%, 12%, 18%, and 28%. Some items are exempt or at 0%." },
      { question: "What is the difference between CGST and SGST?", answer: "For intra-state transactions, GST is split equally between CGST (Central) and SGST (State)." },
      { question: "How to calculate GST on a product?", answer: "GST Amount = (Base Price × GST Rate) / 100. Total = Base Price + GST Amount." },
      { question: "How to remove GST from a GST-inclusive price?", answer: "Original Price = GST-Inclusive Price / (1 + GST Rate/100)" },
    ],
    relatedTools: ["tax-calculator", "roi-calculator", "loan-calculator"],
    benefits: ["Accurate GST billing", "Tax compliance", "Invoice preparation", "Price planning"],
  },
  {
    slug: "tax-calculator",
    name: "Income Tax Calculator",
    description:
      "Calculate Indian income tax for FY 2024-25 online. Compare old and new tax regime to find which saves you more tax.",
    shortDescription: "Calculate income tax under old and new tax regime.",
    category: "finance-tools",
    categoryName: "Finance Tools",
    keywords: ["income tax calculator india", "tax calculator 2024-25", "old vs new tax regime", "it calculator india"],
    icon: "FileText",
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
    features: [
      { title: "Both Regimes", description: "Compare old and new tax regime side by side.", icon: "GitCompare" },
      { title: "FY 2024-25", description: "Updated for latest budget and slabs.", icon: "Calendar" },
      { title: "Deductions", description: "Include HRA, 80C, 80D and other deductions.", icon: "MinusCircle" },
      { title: "Regime Recommendation", description: "Get advice on which regime saves more.", icon: "Lightbulb" },
    ],
    howTo: [
      { step: 1, title: "Enter Annual Income", description: "Enter your total annual gross income." },
      { step: 2, title: "Add Deductions", description: "Enter applicable deductions under old regime." },
      { step: 3, title: "Compare & Calculate", description: "See tax under both regimes and choose." },
    ],
    faqs: [
      { question: "Which tax regime is better?", answer: "New regime is beneficial if deductions are less than ₹3.75L. Old regime is better with high 80C, HRA, and home loan deductions." },
      { question: "What are the new tax slabs for FY 2024-25?", answer: "New regime: 0-3L (0%), 3-7L (5%), 7-10L (10%), 10-12L (15%), 12-15L (20%), 15L+ (30%)." },
      { question: "What deductions can I claim?", answer: "Under old regime: 80C (₹1.5L), HRA, 80D (health insurance), home loan interest, and more." },
      { question: "Is there standard deduction?", answer: "Yes, ₹75,000 standard deduction is available in both old and new tax regimes for FY 2024-25." },
      { question: "What is surcharge?", answer: "Surcharge applies on income above ₹50L: 10% (50L-1Cr), 15% (1Cr-2Cr), 25% (2Cr-5Cr), 37% (above 5Cr)." },
    ],
    relatedTools: ["gst-calculator", "roi-calculator", "sip-calculator"],
    benefits: ["Maximize tax savings", "Plan investments", "File returns correctly", "Choose right regime"],
  },

  // ── PDF TOOLS ─────────────────────────────────────────────────────────────
  {
    slug: "pdf-compressor",
    name: "PDF Compressor",
    description:
      "Compress PDF files online for free. Reduce PDF file size while maintaining quality. No email required, files deleted after processing.",
    shortDescription: "Reduce PDF file size without losing quality.",
    category: "pdf-tools",
    categoryName: "PDF Tools",
    keywords: ["pdf compressor", "compress pdf online", "reduce pdf size", "pdf file size reducer"],
    icon: "FileDown",
    color: "text-rose-500",
    gradient: "from-rose-500 to-pink-600",
    features: [
      { title: "High Compression", description: "Reduce PDF size by up to 80%.", icon: "TrendingDown" },
      { title: "Quality Options", description: "Choose from 3 compression levels.", icon: "SlidersHorizontal" },
      { title: "Secure", description: "Files deleted immediately after processing.", icon: "Shield" },
      { title: "Up to 100MB", description: "Compress large PDF files.", icon: "FileText" },
    ],
    howTo: [
      { step: 1, title: "Upload PDF", description: "Select or drag-and-drop your PDF file." },
      { step: 2, title: "Choose Level", description: "Select compression level: low, medium, or high." },
      { step: 3, title: "Download", description: "Download the compressed PDF instantly." },
    ],
    faqs: [
      { question: "How much can a PDF be compressed?", answer: "Depending on content, PDFs can be reduced by 20–80%. Image-heavy PDFs compress more than text-only PDFs." },
      { question: "Will compression reduce PDF quality?", answer: "Low compression has minimal quality impact. High compression may slightly reduce image resolution." },
      { question: "Is my PDF secure?", answer: "Yes. Files are deleted from our servers immediately after download. We don't store or access your content." },
      { question: "Is there a file size limit?", answer: "We support PDFs up to 100MB." },
      { question: "Is the tool free?", answer: "Yes, completely free with no registration required." },
    ],
    relatedTools: ["pdf-merger", "pdf-splitter", "pdf-to-word"],
    benefits: ["Easier email sharing", "Faster upload/download", "Cloud storage savings", "Website performance"],
  },
  {
    slug: "pdf-merger",
    name: "PDF Merger",
    description:
      "Merge multiple PDF files into one online for free. Combine and rearrange PDF pages in any order. Fast, secure, and no watermarks.",
    shortDescription: "Combine multiple PDFs into a single file online.",
    category: "pdf-tools",
    categoryName: "PDF Tools",
    keywords: ["pdf merger", "merge pdf online", "combine pdf files", "join pdf", "pdf combiner"],
    icon: "FilePlus",
    color: "text-rose-500",
    gradient: "from-rose-500 to-pink-600",
    features: [
      { title: "Merge up to 20 PDFs", description: "Combine up to 20 PDF files at once.", icon: "Layers" },
      { title: "Drag to Reorder", description: "Rearrange PDF order before merging.", icon: "ArrowUpDown" },
      { title: "No Watermark", description: "Output PDF is clean without watermarks.", icon: "Check" },
      { title: "Secure", description: "Files deleted immediately after merge.", icon: "Shield" },
    ],
    howTo: [
      { step: 1, title: "Upload PDFs", description: "Upload 2 or more PDF files to merge." },
      { step: 2, title: "Arrange Order", description: "Drag and drop to set the desired order." },
      { step: 3, title: "Merge & Download", description: "Click merge and download the combined PDF." },
    ],
    faqs: [
      { question: "How many PDFs can I merge at once?", answer: "You can merge up to 20 PDF files in a single operation." },
      { question: "Will merged PDF maintain original formatting?", answer: "Yes, the merged PDF preserves all formatting, images, and content from original files." },
      { question: "Can I merge password-protected PDFs?", answer: "You'll need to remove password protection first before merging." },
      { question: "Is there a file size limit per PDF?", answer: "Each individual PDF can be up to 50MB, and total upload size is 200MB." },
      { question: "Is the tool free?", answer: "Yes, completely free with no account required." },
    ],
    relatedTools: ["pdf-splitter", "pdf-compressor", "pdf-to-word"],
    benefits: ["Organize documents", "Simplify sharing", "Reduce file count", "Professional presentation"],
  },
  {
    slug: "pdf-splitter",
    name: "PDF Splitter",
    description:
      "Split PDF files online for free. Extract specific pages, split by page range, or split every page into separate PDF files.",
    shortDescription: "Split PDF into multiple files or extract specific pages.",
    category: "pdf-tools",
    categoryName: "PDF Tools",
    keywords: ["pdf splitter", "split pdf online", "extract pdf pages", "pdf page extractor", "split pdf free"],
    icon: "FileMinus",
    color: "text-rose-500",
    gradient: "from-rose-500 to-pink-600",
    features: [
      { title: "Split by Range", description: "Split PDF by custom page ranges.", icon: "Scissors" },
      { title: "Extract Pages", description: "Extract specific pages from PDF.", icon: "FileSearch" },
      { title: "Split Every Page", description: "Create one PDF per page.", icon: "Copy" },
      { title: "Preview Pages", description: "See page thumbnails before splitting.", icon: "Eye" },
    ],
    howTo: [
      { step: 1, title: "Upload PDF", description: "Upload the PDF you want to split." },
      { step: 2, title: "Select Pages", description: "Choose page ranges or specific pages to extract." },
      { step: 3, title: "Split & Download", description: "Download split PDF files as a ZIP." },
    ],
    faqs: [
      { question: "Can I extract a single page from a PDF?", answer: "Yes, simply specify the single page number in the page range field." },
      { question: "How are split files delivered?", answer: "If you create multiple PDFs, they're downloaded as a ZIP archive." },
      { question: "Can I split a 100-page PDF?", answer: "Yes, we support PDFs up to 200 pages and 100MB in size." },
      { question: "Will quality be maintained after splitting?", answer: "Yes, the split PDF pages are identical to the original with no quality loss." },
      { question: "Is the tool free?", answer: "Yes, completely free with no sign-up required." },
    ],
    relatedTools: ["pdf-merger", "pdf-compressor", "pdf-to-word"],
    benefits: ["Share specific sections", "Reduce file size", "Organize content", "Extract important pages"],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word Converter",
    description:
      "Convert PDF to editable Word document online for free. Preserve formatting, fonts, and layout. Download as .docx instantly.",
    shortDescription: "Convert PDF files to editable Word documents online.",
    category: "pdf-tools",
    categoryName: "PDF Tools",
    keywords: ["pdf to word", "convert pdf to word", "pdf to docx", "pdf to word converter free online"],
    icon: "FileOutput",
    color: "text-rose-500",
    gradient: "from-rose-500 to-pink-600",
    features: [
      { title: "Editable Output", description: "Output is a fully editable .docx file.", icon: "Edit" },
      { title: "Format Preserved", description: "Maintains fonts, tables, and layout.", icon: "Layout" },
      { title: "Fast Conversion", description: "Convert PDF to Word in seconds.", icon: "Zap" },
      { title: "Free & Secure", description: "No watermarks, no registration.", icon: "Shield" },
    ],
    howTo: [
      { step: 1, title: "Upload PDF", description: "Select your PDF file to convert." },
      { step: 2, title: "Convert", description: "Click convert to start the process." },
      { step: 3, title: "Download .docx", description: "Download your editable Word document." },
    ],
    faqs: [
      { question: "Is PDF to Word conversion accurate?", answer: "Accuracy depends on PDF complexity. Simple text PDFs convert excellently; complex layouts may need minor edits." },
      { question: "Can I convert scanned PDFs?", answer: "We use OCR technology to handle scanned PDFs, though accuracy depends on scan quality." },
      { question: "Is there a page limit for conversion?", answer: "You can convert PDFs up to 50 pages and 25MB per file." },
      { question: "Will the formatting be preserved?", answer: "We preserve formatting as accurately as possible including fonts, tables, and headings." },
      { question: "Is the tool free?", answer: "Yes, completely free with no account required." },
    ],
    relatedTools: ["word-to-pdf", "pdf-compressor", "pdf-merger"],
    benefits: ["Edit PDF content", "Update documents", "Extract text", "Collaborative editing"],
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF Converter",
    description:
      "Convert Word documents to PDF online for free. Maintain formatting perfectly. Convert .doc and .docx files to PDF instantly.",
    shortDescription: "Convert Word documents to PDF with perfect formatting.",
    category: "pdf-tools",
    categoryName: "PDF Tools",
    keywords: ["word to pdf", "convert word to pdf", "docx to pdf", "doc to pdf converter free online"],
    icon: "FileInput",
    color: "text-rose-500",
    gradient: "from-rose-500 to-pink-600",
    features: [
      { title: "Perfect Formatting", description: "PDF matches your Word document exactly.", icon: "Check" },
      { title: "Supports .doc & .docx", description: "Works with all Word file formats.", icon: "FileText" },
      { title: "Universal PDF", description: "Output works on all devices and viewers.", icon: "Globe" },
      { title: "Fast & Free", description: "Convert in seconds, no registration.", icon: "Zap" },
    ],
    howTo: [
      { step: 1, title: "Upload Word File", description: "Select your .doc or .docx file." },
      { step: 2, title: "Convert", description: "Click convert to generate the PDF." },
      { step: 3, title: "Download PDF", description: "Download your perfect PDF file." },
    ],
    faqs: [
      { question: "What Word formats are supported?", answer: "We support both .doc (Word 97-2003) and .docx (Word 2007+) formats." },
      { question: "Is the PDF formatting accurate?", answer: "Yes, our conversion preserves fonts, images, tables, headers, and page layout." },
      { question: "Can I convert password-protected Word files?", answer: "No, password-protected files must be unlocked before conversion." },
      { question: "Is there a file size limit?", answer: "Word files up to 50MB can be converted." },
      { question: "Is the conversion free?", answer: "Yes, unlimited free conversions with no account required." },
    ],
    relatedTools: ["pdf-to-word", "pdf-compressor", "pdf-merger"],
    benefits: ["Professional sharing", "Universal compatibility", "Archive documents", "Secure distribution"],
  },

  // ── SEO TOOLS ─────────────────────────────────────────────────────────────
  {
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    description:
      "Generate optimized HTML meta tags for SEO online. Create title, description, keywords, Open Graph, and Twitter Card tags instantly.",
    shortDescription: "Generate complete SEO meta tags for any webpage.",
    category: "seo-tools",
    categoryName: "SEO Tools",
    keywords: ["meta tag generator", "seo meta tags", "og tags generator", "twitter card generator", "html meta tags"],
    icon: "Tag",
    color: "text-blue-500",
    gradient: "from-blue-500 to-indigo-600",
    features: [
      { title: "All Meta Tags", description: "Title, description, keywords, robots tags.", icon: "Code2" },
      { title: "Open Graph Tags", description: "Generate OG tags for social media sharing.", icon: "Share2" },
      { title: "Twitter Cards", description: "Generate Twitter card meta tags.", icon: "Twitter" },
      { title: "Copy to Clipboard", description: "One-click copy of generated tags.", icon: "Copy" },
    ],
    howTo: [
      { step: 1, title: "Enter Page Details", description: "Fill in title, description, URL, and keywords." },
      { step: 2, title: "Set Social Tags", description: "Add OG image URL and Twitter card settings." },
      { step: 3, title: "Copy Tags", description: "Copy the generated HTML and paste into your <head>." },
    ],
    faqs: [
      { question: "What is the ideal title tag length?", answer: "Keep title tags between 50–60 characters to avoid truncation in search results." },
      { question: "How long should meta descriptions be?", answer: "Meta descriptions should be 150–160 characters for optimal display in search results." },
      { question: "Are meta keywords still important?", answer: "Google ignores meta keywords, but they may be used by other search engines. Include them as a best practice." },
      { question: "What are Open Graph tags?", answer: "Open Graph tags control how your page appears when shared on Facebook, LinkedIn, and other social platforms." },
      { question: "Do meta tags directly affect rankings?", answer: "Title and description influence CTR which affects rankings. Keywords tag is ignored by major search engines." },
    ],
    relatedTools: ["schema-markup-generator", "robots-txt-generator", "utm-builder"],
    benefits: ["Improve CTR from search", "Better social sharing", "Crawl control", "Brand consistency"],
  },
  {
    slug: "schema-markup-generator",
    name: "Schema Markup Generator",
    description:
      "Generate JSON-LD structured data markup for your website. Support for Article, FAQ, Product, Organization, Breadcrumb, and more schema types.",
    shortDescription: "Generate JSON-LD schema markup for rich search results.",
    category: "seo-tools",
    categoryName: "SEO Tools",
    keywords: ["schema markup generator", "json-ld generator", "structured data generator", "schema.org generator"],
    icon: "Braces",
    color: "text-blue-500",
    gradient: "from-blue-500 to-indigo-600",
    features: [
      { title: "Multiple Schema Types", description: "Article, FAQ, Product, Organization, and more.", icon: "List" },
      { title: "Valid JSON-LD", description: "Generates valid schema.org markup.", icon: "Check" },
      { title: "Google Rich Results", description: "Helps achieve rich snippets in search.", icon: "Star" },
      { title: "Copy & Preview", description: "Copy markup and preview in Google's tester.", icon: "Eye" },
    ],
    howTo: [
      { step: 1, title: "Choose Schema Type", description: "Select the schema type (Article, FAQ, Product, etc.)." },
      { step: 2, title: "Fill Details", description: "Enter the required information for the schema." },
      { step: 3, title: "Copy JSON-LD", description: "Copy the generated markup and add to your page." },
    ],
    faqs: [
      { question: "What is schema markup?", answer: "Schema markup is structured data that helps search engines understand your content and enables rich results." },
      { question: "What is JSON-LD?", answer: "JSON-LD (JavaScript Object Notation for Linked Data) is Google's preferred format for structured data." },
      { question: "Where do I add schema markup?", answer: "Add the <script type='application/ld+json'> block in the <head> or <body> of your HTML page." },
      { question: "Will schema markup improve my rankings?", answer: "Schema doesn't directly improve rankings but can increase CTR through rich results like stars, FAQs, and breadcrumbs." },
      { question: "How do I test schema markup?", answer: "Use Google's Rich Results Test (search.google.com/test/rich-results) to validate your markup." },
    ],
    relatedTools: ["meta-tag-generator", "robots-txt-generator", "xml-sitemap-generator"],
    benefits: ["Rich search snippets", "Higher CTR", "Better search understanding", "Featured snippets"],
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    description:
      "Generate a robots.txt file for your website online for free. Control search engine crawling with proper directives for all major bots.",
    shortDescription: "Generate a robots.txt file to control search crawlers.",
    category: "seo-tools",
    categoryName: "SEO Tools",
    keywords: ["robots txt generator", "create robots.txt", "robots.txt file generator", "seo robots file"],
    icon: "Bot",
    color: "text-blue-500",
    gradient: "from-blue-500 to-indigo-600",
    features: [
      { title: "All Major Bots", description: "Configure rules for Googlebot, Bingbot, and others.", icon: "Globe" },
      { title: "Allow/Disallow", description: "Set crawl rules for specific paths.", icon: "ShieldCheck" },
      { title: "Sitemap Link", description: "Add your sitemap URL to robots.txt.", icon: "Map" },
      { title: "Instant Preview", description: "Preview your robots.txt before copying.", icon: "Eye" },
    ],
    howTo: [
      { step: 1, title: "Select Bots", description: "Choose which search engine bots to configure." },
      { step: 2, title: "Set Rules", description: "Add allow and disallow path rules." },
      { step: 3, title: "Add Sitemap", description: "Include your sitemap URL and copy the file." },
    ],
    faqs: [
      { question: "What is a robots.txt file?", answer: "Robots.txt is a file that tells search engine crawlers which pages or files they can or cannot request from your site." },
      { question: "Where do I place robots.txt?", answer: "Robots.txt must be placed in the root directory of your website (e.g., https://example.com/robots.txt)." },
      { question: "Does robots.txt guarantee pages won't be indexed?", answer: "No. It only instructs bots. Use 'noindex' meta tags to prevent indexing of specific pages." },
      { question: "Can I block specific bots?", answer: "Yes, use 'User-agent: BotName' followed by 'Disallow: /' to block specific crawlers." },
      { question: "Should I allow or block my admin pages?", answer: "Always disallow admin, login, and private pages (e.g., Disallow: /admin/)." },
    ],
    relatedTools: ["xml-sitemap-generator", "meta-tag-generator", "schema-markup-generator"],
    benefits: ["Control crawl budget", "Protect private pages", "Improve indexing", "Better site management"],
  },
  {
    slug: "xml-sitemap-generator",
    name: "XML Sitemap Generator",
    description:
      "Generate an XML sitemap for your website online for free. Improve SEO by helping search engines discover and index all your pages.",
    shortDescription: "Generate XML sitemaps to improve search engine indexing.",
    category: "seo-tools",
    categoryName: "SEO Tools",
    keywords: ["xml sitemap generator", "sitemap generator online", "create xml sitemap", "seo sitemap tool free"],
    icon: "Map",
    color: "text-blue-500",
    gradient: "from-blue-500 to-indigo-600",
    features: [
      { title: "Standard XML Format", description: "Generates valid sitemap.xml format.", icon: "FileCode" },
      { title: "Priority & Frequency", description: "Set priority and change frequency per URL.", icon: "SlidersHorizontal" },
      { title: "Last Modified Date", description: "Include lastmod dates for pages.", icon: "Calendar" },
      { title: "Bulk URL Input", description: "Add multiple URLs at once.", icon: "List" },
    ],
    howTo: [
      { step: 1, title: "Enter URLs", description: "Add all the URLs you want in your sitemap." },
      { step: 2, title: "Set Properties", description: "Set priority, change frequency, and last modified dates." },
      { step: 3, title: "Generate & Download", description: "Download the XML file and upload to your website root." },
    ],
    faqs: [
      { question: "What is an XML sitemap?", answer: "An XML sitemap is a file listing all important URLs on your website, helping search engines find and index them." },
      { question: "How many URLs can a sitemap contain?", answer: "A single sitemap can contain up to 50,000 URLs or be 50MB in size. Use sitemap index for larger sites." },
      { question: "Do I need to submit my sitemap to Google?", answer: "Yes, submit via Google Search Console under 'Sitemaps' for faster indexing." },
      { question: "What priority should I set?", answer: "Use 1.0 for homepage, 0.8 for main pages, 0.6 for secondary pages, and 0.4 for archive pages." },
      { question: "Should I include all pages in my sitemap?", answer: "Only include pages you want indexed. Exclude admin, login, thank-you, and duplicate content pages." },
    ],
    relatedTools: ["robots-txt-generator", "meta-tag-generator", "schema-markup-generator"],
    benefits: ["Faster indexing", "Better crawl coverage", "Discover lost pages", "SEO foundation"],
  },
  {
    slug: "utm-builder",
    name: "UTM Builder",
    description:
      "Build UTM tracking URLs for Google Analytics campaigns. Track source, medium, campaign, term, and content in your analytics instantly.",
    shortDescription: "Build UTM tracking URLs for Google Analytics campaigns.",
    category: "seo-tools",
    categoryName: "SEO Tools",
    keywords: ["utm builder", "utm generator", "utm link builder", "google analytics utm parameters", "campaign url builder"],
    icon: "Link",
    color: "text-blue-500",
    gradient: "from-blue-500 to-indigo-600",
    features: [
      { title: "All UTM Parameters", description: "Source, medium, campaign, term, and content.", icon: "Tag" },
      { title: "URL Validation", description: "Validates the destination URL format.", icon: "Check" },
      { title: "Copy to Clipboard", description: "One-click copy of the generated URL.", icon: "Copy" },
      { title: "URL Shortener", description: "Option to shorten long UTM URLs.", icon: "Link2" },
    ],
    howTo: [
      { step: 1, title: "Enter Website URL", description: "Enter the landing page URL to track." },
      { step: 2, title: "Fill UTM Parameters", description: "Enter campaign source, medium, and name." },
      { step: 3, title: "Copy UTM URL", description: "Copy the generated URL for your campaign." },
    ],
    faqs: [
      { question: "What are UTM parameters?", answer: "UTM parameters are tags added to URLs that let Google Analytics track where website traffic comes from." },
      { question: "What are the 5 UTM parameters?", answer: "utm_source (referrer), utm_medium (channel), utm_campaign (name), utm_term (keywords), utm_content (A/B test)." },
      { question: "Are UTM parameters case sensitive?", answer: "Yes, UTM values are case-sensitive. Use lowercase consistently (e.g., 'email' not 'Email')." },
      { question: "Do UTM parameters affect SEO?", answer: "UTM parameters don't affect SEO, but set canonical tags to prevent duplicate content issues." },
      { question: "Can I use UTM parameters for email campaigns?", answer: "Yes! UTM parameters are especially popular for email campaigns (utm_medium=email)." },
    ],
    relatedTools: ["meta-tag-generator", "xml-sitemap-generator", "keyword-density-checker"],
    benefits: ["Track campaign ROI", "Measure channel performance", "Optimize ad spend", "Data-driven marketing"],
  },
  {
    slug: "keyword-density-checker",
    name: "Keyword Density Checker",
    description:
      "Analyze keyword density in your content online for free. Check keyword frequency, density percentage, and optimize content for SEO.",
    shortDescription: "Analyze keyword frequency and density in your content.",
    category: "seo-tools",
    categoryName: "SEO Tools",
    keywords: ["keyword density checker", "keyword frequency checker", "keyword density tool", "seo keyword analysis"],
    icon: "BarChart2",
    color: "text-blue-500",
    gradient: "from-blue-500 to-indigo-600",
    features: [
      { title: "Real-Time Analysis", description: "Instant keyword density as you type.", icon: "Zap" },
      { title: "1, 2, 3-Word Phrases", description: "Analyze single words and multi-word phrases.", icon: "AlignLeft" },
      { title: "Stop Words Filter", description: "Exclude common words for accurate results.", icon: "Filter" },
      { title: "Density Percentage", description: "See exact percentage for each keyword.", icon: "Percent" },
    ],
    howTo: [
      { step: 1, title: "Paste Content", description: "Paste your article or webpage content." },
      { step: 2, title: "Set Options", description: "Set minimum keyword length and filter stop words." },
      { step: 3, title: "Analyze", description: "View density report for all keywords in your content." },
    ],
    faqs: [
      { question: "What is keyword density?", answer: "Keyword density is the percentage of times a keyword appears on a page compared to the total word count." },
      { question: "What is the ideal keyword density?", answer: "Aim for 1–3% keyword density. Over-optimizing above 3% can be seen as keyword stuffing by Google." },
      { question: "Does keyword density affect rankings?", answer: "It's a minor factor. Natural usage matters more than hitting a specific percentage." },
      { question: "What are stop words?", answer: "Stop words are common words like 'the', 'and', 'is' that add no keyword value and should be filtered out." },
      { question: "How many keywords should I target per page?", answer: "Focus on 1 primary keyword and 3–5 related secondary keywords per page for best results." },
    ],
    relatedTools: ["meta-tag-generator", "schema-markup-generator", "utm-builder"],
    benefits: ["Avoid keyword stuffing", "Optimize content", "Improve relevance", "SEO content audit"],
  },

  // ── DEVELOPER TOOLS ───────────────────────────────────────────────────────
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description:
      "Format, validate, and beautify JSON online for free. Minify JSON, view tree structure, and fix JSON errors instantly in your browser.",
    shortDescription: "Format, validate, and beautify JSON data online.",
    category: "developer-tools",
    categoryName: "Developer Tools",
    keywords: ["json formatter", "json beautifier", "json validator", "format json online", "json pretty print"],
    icon: "Braces",
    color: "text-orange-500",
    gradient: "from-orange-500 to-amber-600",
    features: [
      { title: "Format & Beautify", description: "Indent and format JSON for readability.", icon: "AlignLeft" },
      { title: "Validate JSON", description: "Detect and highlight JSON errors.", icon: "CheckCircle" },
      { title: "Minify JSON", description: "Compress JSON by removing whitespace.", icon: "Minimize2" },
      { title: "Tree View", description: "Explore JSON structure in tree format.", icon: "GitBranch" },
    ],
    howTo: [
      { step: 1, title: "Paste JSON", description: "Paste your JSON data in the input area." },
      { step: 2, title: "Format or Minify", description: "Click format to beautify or minify to compress." },
      { step: 3, title: "Copy Result", description: "Copy the formatted JSON to your clipboard." },
    ],
    faqs: [
      { question: "What is JSON?", answer: "JSON (JavaScript Object Notation) is a lightweight data format used for data exchange between applications." },
      { question: "How do I fix invalid JSON?", answer: "Our validator highlights errors. Common issues include missing quotes, trailing commas, and unmatched brackets." },
      { question: "What is JSON minification?", answer: "Minification removes whitespace and newlines to reduce JSON file size, useful for API responses." },
      { question: "Is my JSON data secure?", answer: "Yes, all processing happens locally in your browser. Your JSON never leaves your device." },
      { question: "Can I format very large JSON files?", answer: "Our tool handles JSON up to 1MB efficiently in the browser." },
    ],
    relatedTools: ["password-generator", "uuid-generator", "meta-tag-generator"],
    benefits: ["Debug API responses", "Readable code", "Data validation", "Development workflow"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description:
      "Generate strong, secure, random passwords online. Customize length, character sets, and create multiple passwords instantly.",
    shortDescription: "Generate strong cryptographically secure random passwords.",
    category: "developer-tools",
    categoryName: "Developer Tools",
    keywords: ["password generator", "random password generator", "strong password generator", "secure password creator"],
    icon: "KeyRound",
    color: "text-orange-500",
    gradient: "from-orange-500 to-amber-600",
    features: [
      { title: "Crypto Secure", description: "Uses Web Crypto API for true randomness.", icon: "Shield" },
      { title: "Customizable", description: "Set length, and character types.", icon: "SlidersHorizontal" },
      { title: "Strength Meter", description: "Visual password strength indicator.", icon: "BarChart2" },
      { title: "Bulk Generate", description: "Generate up to 10 passwords at once.", icon: "Copy" },
    ],
    howTo: [
      { step: 1, title: "Set Length", description: "Choose password length (8–128 characters)." },
      { step: 2, title: "Choose Character Types", description: "Select uppercase, lowercase, numbers, and symbols." },
      { step: 3, title: "Generate & Copy", description: "Click generate and copy your secure password." },
    ],
    faqs: [
      { question: "Is the password generator secure?", answer: "Yes, we use the Web Crypto API's getRandomValues() which provides cryptographically secure random numbers." },
      { question: "What makes a strong password?", answer: "A strong password is 16+ characters long and includes uppercase, lowercase, numbers, and special symbols." },
      { question: "Are generated passwords stored?", answer: "No. Passwords are generated in your browser and never transmitted to our servers." },
      { question: "What password length should I use?", answer: "Use at least 16 characters for sensitive accounts like banking and email. 12+ for general accounts." },
      { question: "Should I use a password manager?", answer: "Yes, using a password manager with unique passwords for each site is the best security practice." },
    ],
    relatedTools: ["uuid-generator", "json-formatter", "meta-tag-generator"],
    benefits: ["Account security", "Prevent breaches", "Easy random generation", "Policy compliance"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description:
      "Generate UUID v4 (random) universally unique identifiers online for free. Generate single or bulk UUIDs instantly with one click.",
    shortDescription: "Generate UUID v4 unique identifiers instantly online.",
    category: "developer-tools",
    categoryName: "Developer Tools",
    keywords: ["uuid generator", "guid generator", "uuid v4 generator", "unique id generator online", "random uuid"],
    icon: "Hash",
    color: "text-orange-500",
    gradient: "from-orange-500 to-amber-600",
    features: [
      { title: "UUID v4 Random", description: "Cryptographically random UUID generation.", icon: "Shuffle" },
      { title: "Bulk Generation", description: "Generate up to 100 UUIDs at once.", icon: "Layers" },
      { title: "Multiple Formats", description: "With/without hyphens, uppercase/lowercase.", icon: "AlignLeft" },
      { title: "Copy All", description: "Copy single or all UUIDs with one click.", icon: "Copy" },
    ],
    howTo: [
      { step: 1, title: "Set Quantity", description: "Choose how many UUIDs to generate (1–100)." },
      { step: 2, title: "Choose Format", description: "Select format: standard, no hyphens, or uppercase." },
      { step: 3, title: "Generate & Copy", description: "Generate and copy UUIDs to clipboard." },
    ],
    faqs: [
      { question: "What is a UUID?", answer: "UUID (Universally Unique Identifier) is a 128-bit identifier that is practically guaranteed to be unique across all systems." },
      { question: "What is UUID v4?", answer: "UUID v4 is randomly generated. It's the most commonly used version for general-purpose unique IDs." },
      { question: "Can two generated UUIDs be the same?", answer: "The probability is astronomically low (1 in 5.3×10^36), making collisions virtually impossible in practice." },
      { question: "Are UUIDs case sensitive?", answer: "UUIDs are typically lowercase but are case-insensitive. Both representations refer to the same identifier." },
      { question: "What is a GUID?", answer: "GUID (Globally Unique Identifier) is Microsoft's term for UUID. They are functionally identical." },
    ],
    relatedTools: ["password-generator", "json-formatter", "qr-code-generator"],
    benefits: ["Database primary keys", "API token generation", "Session management", "File naming"],
  },

  // ── UTILITY TOOLS ─────────────────────────────────────────────────────────
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description:
      "Generate QR codes online for free. Create QR codes for URLs, text, email, phone, WiFi, and more. Download as PNG instantly.",
    shortDescription: "Generate QR codes for URLs, text, and more instantly.",
    category: "utility-tools",
    categoryName: "Utility Tools",
    keywords: ["qr code generator", "free qr code generator", "create qr code", "qr code maker", "qr code online"],
    icon: "QrCode",
    color: "text-cyan-500",
    gradient: "from-cyan-500 to-teal-600",
    features: [
      { title: "Multiple Data Types", description: "URL, text, email, phone, WiFi QR codes.", icon: "List" },
      { title: "Custom Colors", description: "Customize QR code and background color.", icon: "Palette" },
      { title: "Download PNG", description: "Download high-resolution PNG QR code.", icon: "Download" },
      { title: "Error Correction", description: "4 levels of error correction for damaged codes.", icon: "ShieldCheck" },
    ],
    howTo: [
      { step: 1, title: "Select Type", description: "Choose QR type: URL, text, email, or phone." },
      { step: 2, title: "Enter Content", description: "Enter the content you want to encode." },
      { step: 3, title: "Download", description: "Preview and download your QR code as PNG." },
    ],
    faqs: [
      { question: "What can I encode in a QR code?", answer: "URLs, plain text, email addresses, phone numbers, SMS messages, WiFi credentials, and vCards." },
      { question: "How long does a QR code last?", answer: "QR codes don't expire. As long as the destination URL remains active, the QR code will work indefinitely." },
      { question: "Can I customize QR code colors?", answer: "Yes, you can change the foreground and background colors of your QR code." },
      { question: "What size QR code image is best for printing?", answer: "For print, use at least 300×300 pixels. For business cards, 500×500px minimum." },
      { question: "Are the generated QR codes free to use?", answer: "Yes, all generated QR codes are free to use for personal and commercial purposes." },
    ],
    relatedTools: ["uuid-generator", "utm-builder", "meta-tag-generator"],
    benefits: ["Offline-to-online bridge", "Contactless sharing", "Marketing campaigns", "Easy scanning"],
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((t) => t.category === categorySlug);
}

export function getRelatedTools(slugs: string[]): Tool[] {
  return slugs.map((s) => tools.find((t) => t.slug === s)).filter(Boolean) as Tool[];
}

export function getAllToolSlugs(): { category: string; tool: string }[] {
  return tools.map((t) => ({ category: t.category, tool: t.slug }));
}

export const popularTools = [
  "json-formatter",
  "password-generator",
  "image-compressor",
  "sip-calculator",
  "meta-tag-generator",
  "qr-code-generator",
  "emi-calculator",
  "uuid-generator",
];
