"use client";

import { useState } from "react";
import { Copy, Check, Plus, Trash2 } from "lucide-react";

interface Rule {
  id: number;
  path: string;
  type: "allow" | "disallow";
}

export function RobotsTxtGenerator() {
  const [userAgent, setUserAgent] = useState("*");
  const [sitemapUrl, setSitemapUrl] = useState("");
  const [rules, setRules] = useState<Rule[]>([
    { id: 1, path: "/", type: "allow" },
    { id: 2, path: "/admin/", type: "disallow" },
    { id: 3, path: "/api/", type: "disallow" },
  ]);
  const [copied, setCopied] = useState(false);
  let nextId = rules.length + 1;

  const addRule = (type: "allow" | "disallow") => {
    setRules([...rules, { id: nextId++, path: "", type }]);
  };

  const removeRule = (id: number) => {
    setRules(rules.filter(r => r.id !== id));
  };

  const updateRule = (id: number, path: string) => {
    setRules(rules.map(r => r.id === id ? { ...r, path } : r));
  };

  const output = `# robots.txt generated by ToolsHub
# https://toolshub.vercel.app/seo-tools/robots-txt-generator

User-agent: ${userAgent}
${rules.filter(r => r.path).map(r => `${r.type === "allow" ? "Allow" : "Disallow"}: ${r.path}`).join("\n")}
${sitemapUrl ? `\nSitemap: ${sitemapUrl}` : ""}`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label htmlFor="robots-ua" className="block text-sm font-medium mb-1.5">User-Agent</label>
          <input id="robots-ua" type="text" value={userAgent} onChange={e => setUserAgent(e.target.value)} className="w-full px-4 py-2.5 rounded-xl border border-border bg-background text-sm focus:outline-none focus:ring-2 focus:ring-primary/30" aria-label="User agent" />
        </div>
        <div>
          <label htmlFor="robots-sitemap" className="block text-sm font-medium mb-1.5">Sitemap URL</label>
          <input id="robots-sitemap" type="url" value={sitemapUrl} onChange={e => setSitemapUrl(e.target.value)} placeholder="https://example.com/sitemap.xml" className="w-full px-4 py-2.5 rounded-xl border border-border bg-background text-sm focus:outline-none focus:ring-2 focus:ring-primary/30" aria-label="Sitemap URL" />
        </div>
      </div>
      <div>
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-sm font-medium">Rules</h3>
          <div className="flex gap-2">
            <button onClick={() => addRule("allow")} className="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-medium rounded-lg border border-emerald-500/30 text-emerald-600 hover:bg-emerald-500/10 transition-colors"><Plus className="h-3 w-3" /> Allow</button>
            <button onClick={() => addRule("disallow")} className="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-medium rounded-lg border border-rose-500/30 text-rose-600 hover:bg-rose-500/10 transition-colors"><Plus className="h-3 w-3" /> Disallow</button>
          </div>
        </div>
        <div className="space-y-2">
          {rules.map(rule => (
            <div key={rule.id} className="flex items-center gap-2">
              <span className={`text-xs font-medium px-2 py-1 rounded-md ${rule.type === "allow" ? "bg-emerald-500/10 text-emerald-600" : "bg-rose-500/10 text-rose-600"}`}>
                {rule.type === "allow" ? "Allow" : "Disallow"}
              </span>
              <input type="text" value={rule.path} onChange={e => updateRule(rule.id, e.target.value)} placeholder="/path/" className="flex-1 px-3 py-2 rounded-lg border border-border bg-background text-sm focus:outline-none focus:ring-2 focus:ring-primary/30" aria-label={`${rule.type} path`} />
              <button onClick={() => removeRule(rule.id)} className="p-2 rounded-lg text-muted-foreground hover:text-rose-500 hover:bg-rose-500/10 transition-colors" aria-label="Remove rule"><Trash2 className="h-3.5 w-3.5" /></button>
            </div>
          ))}
        </div>
      </div>
      <div>
        <div className="flex items-center justify-between mb-2">
          <h3 className="font-semibold text-sm">Generated robots.txt</h3>
          <button onClick={handleCopy} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors">
            {copied ? <><Check className="h-3 w-3" /> Copied!</> : <><Copy className="h-3 w-3" /> Copy</>}
          </button>
        </div>
        <pre className="p-4 rounded-xl bg-muted/50 border border-border text-xs overflow-x-auto leading-relaxed"><code>{output}</code></pre>
      </div>
    </div>
  );
}
